INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (1, 'Frete', 'http://localhost:53516/RepomLogin.ashx?SubperfilID=', 2, True, 1.00, '')
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (2, 'Postos', 'http://localhost:48905/RepomLogin.ashx?SubperfilID=', 3, True, 1.00, '')
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (3, 'Embarcadores', 'http://localhost:53516/RepomLogin.ashx?SubperfilID=', 6, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (4, 'Contratados', '/express/SiteContratados/home.asp', 4, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (5, 'Banco', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (6, 'Esso', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (7, 'Vale Pedágio', ' ', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (8, 'Texaco', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (9, 'CallCenter', '/express/callCenter/Home.asp', 4, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (10, 'Intranet', '/express/intranet/Home.asp', 4, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (11, 'Agenda Desembarque', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (12, 'Produtor CIF', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (13, 'Call Center - Contratado', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (14, 'Posto - TEF', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (15, 'Portal CIOT', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (16, 'Intranet 2', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (17, 'Intranet - Financeiro', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (18, 'Vale Pedágio - Aplicativo', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (19, 'Cartao Adicional', '/express/intranet/Home.asp', 5, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (20, 'Frete - PME', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (21, 'Intranet - Sustentação', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (22, 'Parceiro', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (23, 'Extranet', '', 0, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (24, 'Aplicativo', '', 1, True, 1.00, 'Usuário aplicativo WebApi, quando o usuário não possui vinculo na Repom(anônimo).')
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (25, 'Documentação', '', 1, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (26, 'Documentação', '', 1, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (27, 'Portal Pedágio Eletrôncio Atendimento', '/Repom.Pedagio.Web.PA', 0, True, 1.00, 'Portal do Pedágio Eletrônico do Ponto de Atendimento')
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (99, 'Controle de usuários Repom', 'http://localhost:53516/RepomLogin.ashx?SubperfilID=', 1, True, 1.00, NULL)
INSERT INTO Perfil (ID, Descricao, Url, Ordenacao, Ativo, Versao, Observacao) VALUES (600, 'Documentação', '', 1, True, 1.00, NULL)